// Code generated by radius-dict-gen. DO NOT EDIT.

package riverstone

import (
	"strconv"

	"layeh.com/radius"
	"layeh.com/radius/rfc2865"
)

const (
	_Riverstone_VendorID = 5567
)

func _Riverstone_AddVendor(p *radius.Packet, typ byte, attr radius.Attribute) (err error) {
	var vsa radius.Attribute
	vendor := make(radius.Attribute, 2+len(attr))
	vendor[0] = typ
	vendor[1] = byte(len(vendor))
	copy(vendor[2:], attr)
	vsa, err = radius.NewVendorSpecific(_Riverstone_VendorID, vendor)
	if err != nil {
		return
	}
	p.Add(rfc2865.VendorSpecific_Type, vsa)
	return
}

func _Riverstone_GetsVendor(p *radius.Packet, typ byte) (values []radius.Attribute) {
	for _, avp := range p.Attributes {
		if avp.Type != rfc2865.VendorSpecific_Type {
			continue
		}
		attr := avp.Attribute
		vendorID, vsa, err := radius.VendorSpecific(attr)
		if err != nil || vendorID != _Riverstone_VendorID {
			continue
		}
		for len(vsa) >= 3 {
			vsaTyp, vsaLen := vsa[0], vsa[1]
			if int(vsaLen) > len(vsa) || vsaLen < 3 {
				break
			}
			if vsaTyp == typ {
				values = append(values, vsa[2:int(vsaLen)])
			}
			vsa = vsa[int(vsaLen):]
		}
	}
	return
}

func _Riverstone_LookupVendor(p *radius.Packet, typ byte) (attr radius.Attribute, ok bool) {
	for _, avp := range p.Attributes {
		if avp.Type != rfc2865.VendorSpecific_Type {
			continue
		}
		attr := avp.Attribute
		vendorID, vsa, err := radius.VendorSpecific(attr)
		if err != nil || vendorID != _Riverstone_VendorID {
			continue
		}
		for len(vsa) >= 3 {
			vsaTyp, vsaLen := vsa[0], vsa[1]
			if int(vsaLen) > len(vsa) || vsaLen < 3 {
				break
			}
			if vsaTyp == typ {
				return vsa[2:int(vsaLen)], true
			}
			vsa = vsa[int(vsaLen):]
		}
	}
	return
}

func _Riverstone_SetVendor(p *radius.Packet, typ byte, attr radius.Attribute) (err error) {
	for i := 0; i < len(p.Attributes); {
		avp := p.Attributes[i]
		if avp.Type != rfc2865.VendorSpecific_Type {
			i++
			continue
		}
		vendorID, vsa, err := radius.VendorSpecific(avp.Attribute)
		if err != nil || vendorID != _Riverstone_VendorID {
			i++
			continue
		}
		for j := 0; len(vsa[j:]) >= 3; {
			vsaTyp, vsaLen := vsa[0], vsa[1]
			if int(vsaLen) > len(vsa[j:]) || vsaLen < 3 {
				i++
				break
			}
			if vsaTyp == typ {
				vsa = append(vsa[:j], vsa[j+int(vsaLen):]...)
			}
			j += int(vsaLen)
		}
		if len(vsa) > 0 {
			copy(avp.Attribute[4:], vsa)
			i++
		} else {
			p.Attributes = append(p.Attributes[:i], p.Attributes[i+i:]...)
		}
	}
	return _Riverstone_AddVendor(p, typ, attr)
}

func _Riverstone_DelVendor(p *radius.Packet, typ byte) {
vsaLoop:
	for i := 0; i < len(p.Attributes); {
		avp := p.Attributes[i]
		if avp.Type != rfc2865.VendorSpecific_Type {
			i++
			continue
		}
		vendorID, vsa, err := radius.VendorSpecific(avp.Attribute)
		if err != nil || vendorID != _Riverstone_VendorID {
			i++
			continue
		}
		offset := 0
		for len(vsa[offset:]) >= 3 {
			vsaTyp, vsaLen := vsa[offset], vsa[offset+1]
			if int(vsaLen) > len(vsa) || vsaLen < 3 {
				continue vsaLoop
			}
			if vsaTyp == typ {
				copy(vsa[offset:], vsa[offset+int(vsaLen):])
				vsa = vsa[:len(vsa)-int(vsaLen)]
			} else {
				offset += int(vsaLen)
			}
		}
		if offset == 0 {
			p.Attributes = append(p.Attributes[:i], p.Attributes[i+1:]...)
		} else {
			i++
		}
	}
	return
}

func RiverstoneCommand_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Riverstone_AddVendor(p, 1, a)
}

func RiverstoneCommand_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Riverstone_AddVendor(p, 1, a)
}

func RiverstoneCommand_Get(p *radius.Packet) (value []byte) {
	value, _ = RiverstoneCommand_Lookup(p)
	return
}

func RiverstoneCommand_GetString(p *radius.Packet) (value string) {
	value, _ = RiverstoneCommand_LookupString(p)
	return
}

func RiverstoneCommand_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Riverstone_GetsVendor(p, 1) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func RiverstoneCommand_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Riverstone_GetsVendor(p, 1) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func RiverstoneCommand_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Riverstone_LookupVendor(p, 1)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func RiverstoneCommand_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Riverstone_LookupVendor(p, 1)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func RiverstoneCommand_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Riverstone_SetVendor(p, 1, a)
}

func RiverstoneCommand_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Riverstone_SetVendor(p, 1, a)
}

func RiverstoneCommand_Del(p *radius.Packet) {
	_Riverstone_DelVendor(p, 1)
}

func RiverstoneSystemEvent_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Riverstone_AddVendor(p, 2, a)
}

func RiverstoneSystemEvent_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Riverstone_AddVendor(p, 2, a)
}

func RiverstoneSystemEvent_Get(p *radius.Packet) (value []byte) {
	value, _ = RiverstoneSystemEvent_Lookup(p)
	return
}

func RiverstoneSystemEvent_GetString(p *radius.Packet) (value string) {
	value, _ = RiverstoneSystemEvent_LookupString(p)
	return
}

func RiverstoneSystemEvent_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Riverstone_GetsVendor(p, 2) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func RiverstoneSystemEvent_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Riverstone_GetsVendor(p, 2) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func RiverstoneSystemEvent_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Riverstone_LookupVendor(p, 2)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func RiverstoneSystemEvent_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Riverstone_LookupVendor(p, 2)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func RiverstoneSystemEvent_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Riverstone_SetVendor(p, 2, a)
}

func RiverstoneSystemEvent_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Riverstone_SetVendor(p, 2, a)
}

func RiverstoneSystemEvent_Del(p *radius.Packet) {
	_Riverstone_DelVendor(p, 2)
}

func RiverstoneSNMPConfigChange_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Riverstone_AddVendor(p, 3, a)
}

func RiverstoneSNMPConfigChange_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Riverstone_AddVendor(p, 3, a)
}

func RiverstoneSNMPConfigChange_Get(p *radius.Packet) (value []byte) {
	value, _ = RiverstoneSNMPConfigChange_Lookup(p)
	return
}

func RiverstoneSNMPConfigChange_GetString(p *radius.Packet) (value string) {
	value, _ = RiverstoneSNMPConfigChange_LookupString(p)
	return
}

func RiverstoneSNMPConfigChange_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Riverstone_GetsVendor(p, 3) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func RiverstoneSNMPConfigChange_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Riverstone_GetsVendor(p, 3) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func RiverstoneSNMPConfigChange_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Riverstone_LookupVendor(p, 3)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func RiverstoneSNMPConfigChange_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Riverstone_LookupVendor(p, 3)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func RiverstoneSNMPConfigChange_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Riverstone_SetVendor(p, 3, a)
}

func RiverstoneSNMPConfigChange_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Riverstone_SetVendor(p, 3, a)
}

func RiverstoneSNMPConfigChange_Del(p *radius.Packet) {
	_Riverstone_DelVendor(p, 3)
}

type RiverstoneUserLevel uint32

var RiverstoneUserLevel_Strings = map[RiverstoneUserLevel]string{}

func (a RiverstoneUserLevel) String() string {
	if str, ok := RiverstoneUserLevel_Strings[a]; ok {
		return str
	}
	return "RiverstoneUserLevel(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func RiverstoneUserLevel_Add(p *radius.Packet, value RiverstoneUserLevel) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Riverstone_AddVendor(p, 4, a)
}

func RiverstoneUserLevel_Get(p *radius.Packet) (value RiverstoneUserLevel) {
	value, _ = RiverstoneUserLevel_Lookup(p)
	return
}

func RiverstoneUserLevel_Gets(p *radius.Packet) (values []RiverstoneUserLevel, err error) {
	var i uint32
	for _, attr := range _Riverstone_GetsVendor(p, 4) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, RiverstoneUserLevel(i))
	}
	return
}

func RiverstoneUserLevel_Lookup(p *radius.Packet) (value RiverstoneUserLevel, err error) {
	a, ok := _Riverstone_LookupVendor(p, 4)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = RiverstoneUserLevel(i)
	return
}

func RiverstoneUserLevel_Set(p *radius.Packet, value RiverstoneUserLevel) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Riverstone_SetVendor(p, 4, a)
}

func RiverstoneUserLevel_Del(p *radius.Packet) {
	_Riverstone_DelVendor(p, 4)
}
