// Code generated by radius-dict-gen. DO NOT EDIT.

package meinberg

import (
	"strconv"

	"layeh.com/radius"
	"layeh.com/radius/rfc2865"
)

const (
	_Meinberg_VendorID = 5597
)

func _Meinberg_AddVendor(p *radius.Packet, typ byte, attr radius.Attribute) (err error) {
	var vsa radius.Attribute
	vendor := make(radius.Attribute, 2+len(attr))
	vendor[0] = typ
	vendor[1] = byte(len(vendor))
	copy(vendor[2:], attr)
	vsa, err = radius.NewVendorSpecific(_Meinberg_VendorID, vendor)
	if err != nil {
		return
	}
	p.Add(rfc2865.VendorSpecific_Type, vsa)
	return
}

func _Meinberg_GetsVendor(p *radius.Packet, typ byte) (values []radius.Attribute) {
	for _, attr := range p.Attributes[rfc2865.VendorSpecific_Type] {
		vendorID, vsa, err := radius.VendorSpecific(attr)
		if err != nil || vendorID != _Meinberg_VendorID {
			continue
		}
		for len(vsa) >= 3 {
			vsaTyp, vsaLen := vsa[0], vsa[1]
			if int(vsaLen) > len(vsa) || vsaLen < 3 {
				break
			}
			if vsaTyp == typ {
				values = append(values, vsa[2:int(vsaLen)])
			}
			vsa = vsa[int(vsaLen):]
		}
	}
	return
}

func _Meinberg_LookupVendor(p *radius.Packet, typ byte) (attr radius.Attribute, ok bool) {
	for _, a := range p.Attributes[rfc2865.VendorSpecific_Type] {
		vendorID, vsa, err := radius.VendorSpecific(a)
		if err != nil || vendorID != _Meinberg_VendorID {
			continue
		}
		for len(vsa) >= 3 {
			vsaTyp, vsaLen := vsa[0], vsa[1]
			if int(vsaLen) > len(vsa) || vsaLen < 3 {
				break
			}
			if vsaTyp == typ {
				return vsa[2:int(vsaLen)], true
			}
			vsa = vsa[int(vsaLen):]
		}
	}
	return
}

func _Meinberg_SetVendor(p *radius.Packet, typ byte, attr radius.Attribute) (err error) {
	for i := 0; i < len(p.Attributes[rfc2865.VendorSpecific_Type]); {
		vendorID, vsa, err := radius.VendorSpecific(p.Attributes[rfc2865.VendorSpecific_Type][i])
		if err != nil || vendorID != _Meinberg_VendorID {
			i++
			continue
		}
		for j := 0; len(vsa[j:]) >= 3; {
			vsaTyp, vsaLen := vsa[0], vsa[1]
			if int(vsaLen) > len(vsa[j:]) || vsaLen < 3 {
				i++
				break
			}
			if vsaTyp == typ {
				vsa = append(vsa[:j], vsa[j+int(vsaLen):]...)
			}
			j += int(vsaLen)
		}
		if len(vsa) > 0 {
			copy(p.Attributes[rfc2865.VendorSpecific_Type][i][4:], vsa)
			i++
		} else {
			p.Attributes[rfc2865.VendorSpecific_Type] = append(p.Attributes[rfc2865.VendorSpecific_Type][:i], p.Attributes[rfc2865.VendorSpecific_Type][i+i:]...)
		}
	}
	return _Meinberg_AddVendor(p, typ, attr)
}

func _Meinberg_DelVendor(p *radius.Packet, typ byte) {
vsaLoop:
	for i := 0; i < len(p.Attributes[rfc2865.VendorSpecific_Type]); {
		attr := p.Attributes[rfc2865.VendorSpecific_Type][i]
		vendorID, vsa, err := radius.VendorSpecific(attr)
		if err != nil || vendorID != _Meinberg_VendorID {
			continue
		}
		offset := 0
		for len(vsa[offset:]) >= 3 {
			vsaTyp, vsaLen := vsa[offset], vsa[offset+1]
			if int(vsaLen) > len(vsa) || vsaLen < 3 {
				continue vsaLoop
			}
			if vsaTyp == typ {
				copy(vsa[offset:], vsa[offset+int(vsaLen):])
				vsa = vsa[:len(vsa)-int(vsaLen)]
			} else {
				offset += int(vsaLen)
			}
		}
		if offset == 0 {
			p.Attributes[rfc2865.VendorSpecific_Type] = append(p.Attributes[rfc2865.VendorSpecific_Type][:i], p.Attributes[rfc2865.VendorSpecific_Type][i+1:]...)
		} else {
			i++
		}
	}
	return
}

type MBGManagementPrivilegeLevel uint32

var MBGManagementPrivilegeLevel_Strings = map[MBGManagementPrivilegeLevel]string{}

func (a MBGManagementPrivilegeLevel) String() string {
	if str, ok := MBGManagementPrivilegeLevel_Strings[a]; ok {
		return str
	}
	return "MBGManagementPrivilegeLevel(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func MBGManagementPrivilegeLevel_Add(p *radius.Packet, value MBGManagementPrivilegeLevel) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Meinberg_AddVendor(p, 1, a)
}

func MBGManagementPrivilegeLevel_Get(p *radius.Packet) (value MBGManagementPrivilegeLevel) {
	value, _ = MBGManagementPrivilegeLevel_Lookup(p)
	return
}

func MBGManagementPrivilegeLevel_Gets(p *radius.Packet) (values []MBGManagementPrivilegeLevel, err error) {
	var i uint32
	for _, attr := range _Meinberg_GetsVendor(p, 1) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, MBGManagementPrivilegeLevel(i))
	}
	return
}

func MBGManagementPrivilegeLevel_Lookup(p *radius.Packet) (value MBGManagementPrivilegeLevel, err error) {
	a, ok := _Meinberg_LookupVendor(p, 1)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = MBGManagementPrivilegeLevel(i)
	return
}

func MBGManagementPrivilegeLevel_Set(p *radius.Packet, value MBGManagementPrivilegeLevel) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Meinberg_SetVendor(p, 1, a)
}

func MBGManagementPrivilegeLevel_Del(p *radius.Packet) {
	_Meinberg_DelVendor(p, 1)
}
